## -*- encoding: utf-8 -*-


# This file was *autogenerated* from the file March30.sagetex.sage
from sage.all_cmdline import *   # import sage library

## This file (March30.sagetex.sage) was *autogenerated* from March30.tex with sagetex.sty version 2019/01/09 v3.3.
import sagetex
_st_ = sagetex.SageTeXProcessor('March30', version='2019/01/09 v3.3', version_check=True)
_st_.endofdoc()

