## -*- encoding: utf-8 -*-


# This file was *autogenerated* from the file quadraticreciprocity.sagetex.sage
from sage.all_cmdline import *   # import sage library

## This file (quadraticreciprocity.sagetex.sage) was *autogenerated* from quadraticreciprocity.tex with sagetex.sty version 2019/01/09 v3.3.
import sagetex
_st_ = sagetex.SageTeXProcessor('quadraticreciprocity', version='2019/01/09 v3.3', version_check=True)
_st_.endofdoc()

