## -*- encoding: utf-8 -*-


# This file was *autogenerated* from the file April13.sagetex.sage
from sage.all_cmdline import *   # import sage library

## This file (April13.sagetex.sage) was *autogenerated* from April13.tex with sagetex.sty version 2019/01/09 v3.3.
import sagetex
_st_ = sagetex.SageTeXProcessor('April13', version='2019/01/09 v3.3', version_check=True)
_st_.endofdoc()

